version: '3.7'
services:
  nestapp:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-app-docker
    container_name: nestapp
    restart: always
    tty: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    working_dir: /var/www/nest-app
    environment:
      SERVICE_NAME: nestapp
      SERVICE_TAGS: dev
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
    volumes:
      - ./:/var/www/nest-app
      - /var/www/nest-app/node_modules
    networks:
      - nest-app-network

  redis:
    image: redis:latest
    container_name: redis
    command: [
      "redis-server",
      "--bind",
      "redis",
      "--port",
      "6379"
    ]
    volumes:
      - red_data:/var/lib/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - nest-app-network

networks:
  nest-app-network:
    driver: bridge
volumes:
  red_data: {}
