version: "3.3"
services:
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /node_modules
    restart: on-failure
    container_name: frontend
    networks:
      - nest-app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: yarn start:dev
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: backend
    volumes:
      - /node_modules
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
    networks:
      - nest-app-network

  mongo:
    image: 'mongo'
    container_name: mongo-db
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    env_file:
      - ./backend/.env
    networks:
      - nest-app-network

  redis:
    image: redis:latest
    container_name: redis
    command: [
        "redis-server",
        "--bind",
        "redis",
        "--port",
        "6379"
    ]
    volumes:
      - red_data:/var/lib/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - nest-app-network

networks:
  nest-app-network:
    driver: bridge
    name: nest-app-network
volumes:
  mongodb-data:
    name: mongodb-data
  red_data: {}
