version: "3.3"
services:
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /node_modules
    restart: on-failure
    container_name: frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: yarn start:dev
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: backend
    volumes:
      - /node_modules
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
  mongo:
    image: 'mongo'
    container_name: 'mongo-db'
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    env_file:
      - ./backend/.env
