import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-edit',
  templateUrl: './edit.component.html',
  styleUrls: ['./edit.component.scss'],
})
export class EditComponent implements OnInit {
  public listCards: any[] = [
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'small',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'large',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'large',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'small',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'small',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'small',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'small',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'small',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'small',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'medium',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'small',
    },
    {
      owner: undefined,
      title: 'title',
      image: './assets/img/upper-right-arrow.png',
      description: 'description',
      price: 1200,
      created: new Date(),
      availableQuantity: 1,
      size: 'large',
    },
  ];

  constructor() {}

  ngOnInit() {}
}
